spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://9.9.9.9:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx3cc7b51a7d4e9eca
  mpAppSecret: ba6edc5678e617d38c1b85e8268dc491
